### ISSUE TITLE
Prefeb Packed Avatar 

### ISSUE THREAD

**Issue by kibalab** [euan142/LazyOptimiser#4]
In case of avatars packed with Prefab
Misplaced mesh when merging meshes after Unpack Prefa
![-1](https://user-images.githubusercontent.com/31209389/178668449-8d56133d-6aef-4e0f-a78b-034be8ee3dfd.png)

**Comment by euan142** [comment]
This appears to be two things,
1. The bind poses were being recalculated on mesh merging, this involved some questionable resetting of scale to the bones. During a refactor of mesh merging I've altered it not to recalculate them, this appears to fix a good bit of the weirdness seen above.
2. Different skinned mesh renderers have different scales, for above it's the hair and tail vs everything else. The issue is when merging currently that scale difference causes issues. I've put in a temporary solution that avoids merging differently scaled skinned meshes. I'm going to look into what needs done to merge things properly

**Comment by euan142** [comment]
I continued on things yesterday testing a few different avatar setups, I'm fairly confident this is resolved now (tested with wolferia as well). If the issue does still remain can reopen the issue
